import { getRandomHumanName } from './humanNames'

const getRandomPercentage = () => `${Math.floor(Math.random() * 101)}%`

const fileNames = [
  `[${getRandomHumanName()}] Application for new CTO`,
  `[${getRandomHumanName()}] salary raise (+${getRandomPercentage()})`,
  `[${getRandomHumanName()}] salary decrease (-${getRandomPercentage()})`,
  `[${getRandomHumanName()}] End probation`,
  `[${getRandomHumanName()}] Terminate contract`,
  `[${getRandomHumanName()}] Layoff`,
  `Security Review`,
  `Compliance Review`,
  `Buy a hotdog`,
  `Lunch plans`,
  `Find a job`,
  `Pretend to work`,
  `Delegate everything`,
  `Page yourself over the intercom`,
  `Find out where the CMO shops & buy exactly the same outfits`,
  `Send email to all telling them what’s poppin’`,
  `Put mosquito netting around your cubicle`,
  `Sit in chair facing a printer all day waiting for documents`,
  `Change e-mail to "xena-goddess-of-fire@"`,
  `If asked to do something, ask if they want fries with that`,
  `Encourage colleagues to join in synchronized chair dancing`,
  `Put garbage can on your desk. Label it "IN"`,
  `Develop an unnatural fear of staplers`,
  `Decorate your office with pictures of ${getRandomHumanName()}`,
  `Decorate your office with pictures of the CEO`,
  `Put decaf in the coffeemaker for 3 weeks`,
  `Compose all e-mail in the form of a Haiku`,
  `If someone asks to do something, ask them to sign a waiver`,
  `Organize company Christmas party at McDonald's Playland`,
  `Talk in a fake British accent at the phone`,
  `Reply to everything someone says with "that's what YOU think.”`,
  `Practice making fax and modem noises`,
  `Highlight irrelevant information in scientific papers`,
  `Staple papers in the middle of the page`,
  `TYPE ONLY IN UPPERCASE`,
  `Pretend to be hypnotized by someone's screen saver`,
  `Domain Knowledge Map`,
  `Technical Strategy`,
  `Product Strategy`,
  `Business Technology`,
  `Big Data`,
  `[${getRandomHumanName()}] wants more money`,
  `[${getRandomHumanName()}] Complaint about ${getRandomHumanName()}`,
  `[${getRandomHumanName()}] Complaint about ${getRandomHumanName()}`,
  `Fire ${getRandomHumanName()} for no reason`,
  `Commercial purchases`,
  `Formulate a vision`,
  `Outline company goals`,
  `Outline timelines`,
  `Develop technical aspects`,
  `Verify all technological practices`,
  `Identify and implement innovation`,
  `[${getRandomHumanName()}] Performance Review`,
  `[${getRandomHumanName()}] Performance Enablement`,
  `Supervise system infrastructure`,
  `Quality assurance`,
  `Legal`,
  `Resign`,
  `Force employees to fill out a pointless survey`,
  `Force employees to fill out an excel sheet that makes no sense`,
  `KPIs and IT budgets`,
  `Communicate tech-strategy`,
  `Make executive decisions`,
]

export const getRandomFileName = () =>
  fileNames[Math.floor(Math.random() * fileNames.length)]
