import React from 'react'

const fileIcons = [
  '/w95-icons/132.ico',
  '/w95-icons/3D Text.ico',
  '/w95-icons/3D computer.ico',
  '/w95-icons/AOL Disc.ico',
  '/w95-icons/AOL List.ico',
  '/w95-icons/AOL.ico',
  '/w95-icons/Accesability.ico',
  '/w95-icons/Agent.ico',
  '/w95-icons/Amex.ico',
  '/w95-icons/Apple.ico',
  '/w95-icons/Arrow (down).ico',
  '/w95-icons/Arrow (up).ico',
  '/w95-icons/Battery (Big on green BG).ico',
  '/w95-icons/Battery (Big on red BG).ico',
  '/w95-icons/Battery (Big without BG).ico',
  '/w95-icons/Battery block.ico',
  '/w95-icons/Beizer.ico',
  '/w95-icons/Blank sheet.ico',
  '/w95-icons/Blank sheets.ico',
  '/w95-icons/Blue dot.ico',
  '/w95-icons/Book 2.ico',
  '/w95-icons/Book 3.ico',
  '/w95-icons/Book 4.ico',
  '/w95-icons/Book Disc.ico',
  '/w95-icons/Book with clock.ico',
  '/w95-icons/Book with phone 2.ico',
  '/w95-icons/Book with phone 3.ico',
  '/w95-icons/Book with phone.ico',
  '/w95-icons/Book.ico',
  '/w95-icons/Books folder.ico',
  '/w95-icons/Box with files.ico',
  '/w95-icons/Briefcase with phone.ico',
  '/w95-icons/Briefcase.ico',
  '/w95-icons/Builder.ico',
  '/w95-icons/Bunch of Keys.ico',
  '/w95-icons/CSi.ico',
  '/w95-icons/Calculator.ico',
  '/w95-icons/Certificate 2.ico',
  '/w95-icons/Certificate.ico',
  '/w95-icons/Change battery.ico',
  '/w95-icons/Chat.ico',
  '/w95-icons/Check mard.ico',
  '/w95-icons/Chemistry with phone.ico',
  '/w95-icons/Chip 2.ico',
  '/w95-icons/Chip Card.ico',
  '/w95-icons/Chip.ico',
  '/w95-icons/Cine-film roll.ico',
  '/w95-icons/Cine-film with music.ico',
  '/w95-icons/Cine-film.ico',
  '/w95-icons/Clipboard with phone.ico',
  '/w95-icons/Close.png',
  '/w95-icons/Color triangle sheet (gray).ico',
  '/w95-icons/Color triangle sheet (white).ico',
  '/w95-icons/Computer Card.ico',
  '/w95-icons/Computer Input.ico',
  '/w95-icons/Computer and Briefcase Sync.ico',
  '/w95-icons/Computer are Earth.ico',
  '/w95-icons/Computer on hand Input.ico',
  '/w95-icons/Computer with phone.ico',
  '/w95-icons/Computer with program.ico',
  '/w95-icons/Computer with programs.ico',
  '/w95-icons/Conference table.ico',
  '/w95-icons/Config program.ico',
  '/w95-icons/Config sheet.ico',
  '/w95-icons/Connect to Database with Phone.ico',
  '/w95-icons/Connect to Earth with phone.ico',
  '/w95-icons/Connections on Earth.ico',
  '/w95-icons/Constructor.ico',
  '/w95-icons/Contact Card.ico',
  '/w95-icons/Content sort (right).ico',
  '/w95-icons/Content sort (up & down).ico',
  '/w95-icons/Controls Folder.ico',
  '/w95-icons/Controls.ico',
  '/w95-icons/Copy.png',
  '/w95-icons/Cross.ico',
  '/w95-icons/Cursor Trail.ico',
  '/w95-icons/Cursor active.ico',
  '/w95-icons/Cursor.ico',
  '/w95-icons/Customize computer.ico',
  '/w95-icons/Cut.png',
  '/w95-icons/Dark Agent.ico',
  '/w95-icons/Deform sheet (H).ico',
  '/w95-icons/Deform sheet (V).ico',
  '/w95-icons/Delete.png',
  '/w95-icons/Deskette Drive.ico',
  '/w95-icons/Desktop.ico',
  '/w95-icons/Destroy letter.ico',
  '/w95-icons/Detector.ico',
  '/w95-icons/Device.ico',
  '/w95-icons/Devices.ico',
  '/w95-icons/Dial-Up Connection (1 of 4).ico',
  '/w95-icons/Dial-Up Connection (2 of 4).ico',
  '/w95-icons/Dial-Up Connection (3 of 4).ico',
  '/w95-icons/Dial-Up Connection (4 of 4).ico',
  '/w95-icons/Dial-Up Folder.ico',
  '/w95-icons/Dial-Up.ico',
  '/w95-icons/Dialog.ico',
  '/w95-icons/Disc Drive 2.ico',
  '/w95-icons/Disc Drive 3.ico',
  '/w95-icons/Disc Drive.ico',
  '/w95-icons/Disc sheet.ico',
  '/w95-icons/Disconnect-Network-Drive.png',
  '/w95-icons/Discover.ico',
  '/w95-icons/Diskette Drive with Diskette.ico',
  '/w95-icons/Diskette.ico',
  '/w95-icons/Diskettes.ico',
  '/w95-icons/Document Locked.ico',
  '/w95-icons/Document to Document.ico',
  '/w95-icons/Document with Earth.ico',
  '/w95-icons/Document with phone.ico',
  '/w95-icons/Documents Folder.ico',
  '/w95-icons/Documents conflict.ico',
  '/w95-icons/Drawing figures.ico',
  '/w95-icons/Drawing green picture.ico',
  '/w95-icons/Drawing on whiteboard.ico',
  '/w95-icons/Drawing red picture.ico',
  '/w95-icons/Drive Graph.ico',
  '/w95-icons/Drive.ico',
  '/w95-icons/Earth (16 colors).ico',
  '/w95-icons/Earth (4 colors).ico',
  '/w95-icons/Earth (8 colors).ico',
  '/w95-icons/Earth Help Program.ico',
  '/w95-icons/Earth Rating Document.ico',
  '/w95-icons/Earth Rating Program.ico',
  '/w95-icons/Earth Rating.ico',
  '/w95-icons/Eject Drive.ico',
  '/w95-icons/Empty Recycle Bin.ico',
  '/w95-icons/Exit.ico',
  '/w95-icons/Explosion (1 of 3).ico',
  '/w95-icons/Explosion (2 of 3).ico',
  '/w95-icons/Explosion (3 of 3).ico',
  '/w95-icons/Fire.ico',
  '/w95-icons/Fax & Modem Sync.ico',
  '/w95-icons/Fax Input.ico',
  '/w95-icons/Fax Warning.ico',
  '/w95-icons/Fax connection.ico',
  '/w95-icons/Fax dialing (1 of 9).ico',
  '/w95-icons/Fax dialing (2 of 9).ico',
  '/w95-icons/Fax dialing (3 of 9).ico',
  '/w95-icons/Fax dialing (4 of 9).ico',
  '/w95-icons/Fax dialing (5 of 9).ico',
  '/w95-icons/Fax dialing (6 of 9).ico',
  '/w95-icons/Fax dialing (7 of 9).ico',
  '/w95-icons/Fax dialing (8 of 9).ico',
  '/w95-icons/Fax dialing (9 of 9).ico',
  '/w95-icons/Fax print.ico',
  '/w95-icons/Fax.ico',
  '/w95-icons/Files from computer.ico',
  '/w95-icons/Filling forms.ico',
  '/w95-icons/Flying Windows.ico',
  '/w95-icons/Folder (hi-res).ico',
  '/w95-icons/Folder Transfer.ico',
  '/w95-icons/Folder catalog 2.ico',
  '/w95-icons/Folder catalog.ico',
  '/w95-icons/Folder to Briefcase.ico',
  '/w95-icons/Folder to Folder & Document to Document.ico',
  '/w95-icons/Folder to Folder.ico',
  '/w95-icons/Folder with files to Folder with files.ico',
  '/w95-icons/Folder-Up.png',
  '/w95-icons/Folder.ico',
  '/w95-icons/Folders conflict.ico',
  '/w95-icons/Folders with files conflict.ico',
  '/w95-icons/Folt Folder.ico',
  '/w95-icons/Font slide.ico',
  '/w95-icons/Font speed.ico',
  '/w95-icons/Font.ico',
  '/w95-icons/Generic.ico',
  '/w95-icons/Globe.ico',
  '/w95-icons/Gray briefcase.ico',
  '/w95-icons/Gray tile.ico',
  '/w95-icons/Handset in hand.ico',
  '/w95-icons/Handset with Dock Station.ico',
  '/w95-icons/Handset with dialog error.ico',
  '/w95-icons/Handset with dialog.ico',
  '/w95-icons/Handset.ico',
  '/w95-icons/Help.ico',
  '/w95-icons/Help 3D.ico',
  '/w95-icons/Help Tile.ico',
  '/w95-icons/Help book.ico',
  '/w95-icons/Help page.ico',
  '/w95-icons/Help sheet.ico',
  '/w95-icons/Highlight Network Drive.ico',
  '/w95-icons/Highlights in program.ico',
  '/w95-icons/Holding.ico',
  '/w95-icons/House with car.ico',
  '/w95-icons/Hoverboard.ico',
  '/w95-icons/IE Disc.ico',
  '/w95-icons/INFO.ico',
  '/w95-icons/IR-Port (Green & Red).ico',
  '/w95-icons/IR-Port (green).ico',
  '/w95-icons/IR-Port Error.ico',
  '/w95-icons/IR-Port Multi-transfer (Red & Red & Red).ico',
  '/w95-icons/IR-Port Share (Green).ico',
  '/w95-icons/IR-Port Warning (Green & Red).ico',
  '/w95-icons/IR-Port Warning (Red & Red).ico',
  '/w95-icons/IR-Port share (Red).ico',
  '/w95-icons/IR-Port transfer (Green & Red).ico',
  '/w95-icons/IR-Port transfer (Red & Red).ico',
  '/w95-icons/IR-Port transfer denied.ico',
  '/w95-icons/IR-Port transfer grogress(Red & Green).ico',
  '/w95-icons/IR-Port transfer progress (Green & Red).ico',
  '/w95-icons/IR-Port transfer progress (Red & Red) (1 of 4).ico',
  '/w95-icons/IR-Port transfer progress (Red & Red) (2 of 4).ico',
  '/w95-icons/IR-Port transfer progress (Red & Red) (3 of 4).ico',
  '/w95-icons/IR-Port transfer progress (Red & Red) (4 of 4).ico',
  '/w95-icons/IR-Port.ico',
  '/w95-icons/Input in Network Net.ico',
  '/w95-icons/Input on Drive.ico',
  '/w95-icons/Installation on computer (discs).ico',
  '/w95-icons/Installation on computer (diskettes).ico',
  '/w95-icons/Installation on computer (stopped).ico',
  '/w95-icons/Installation program.ico',
  '/w95-icons/IpQuestion.ico',
  '/w95-icons/Ir-Port (red).ico',
  '/w95-icons/Ir-Port multi-transfer (Green & Red & Red).ico',
  '/w95-icons/Ir-Port multi-transfer (Red & Green & Green).ico',
  '/w95-icons/JCB.ico',
  '/w95-icons/Java.ico',
  '/w95-icons/Joy controls (down).ico',
  '/w95-icons/Joy controls (left).ico',
  '/w95-icons/Joy controls (off).ico',
  '/w95-icons/Joy controls (on).ico',
  '/w95-icons/Joy controls (right).ico',
  '/w95-icons/Joy controls (up).ico',
  '/w95-icons/Joy pressed.ico',
  '/w95-icons/Joy.ico',
  '/w95-icons/Key in Lock.ico',
  '/w95-icons/Key.ico',
  '/w95-icons/Keyboard.ico',
  '/w95-icons/Keys with Earth.ico',
  '/w95-icons/LAN Connect.ico',
  '/w95-icons/LAN Transfer (1 of 4).ico',
  '/w95-icons/LAN Transfer (2 of 4).ico',
  '/w95-icons/LAN Transfer (3 of 4).ico',
  '/w95-icons/LAN Transfer (4 of 4).ico',
  '/w95-icons/LAN.ico',
  '/w95-icons/Lamp 2.ico',
  '/w95-icons/Lamp with phone.ico',
  '/w95-icons/Lamp.ico',
  '/w95-icons/Laptop Input.ico',
  '/w95-icons/Letter3.ico',
  '/w95-icons/Letter 2.ico',
  '/w95-icons/Letter with phone.ico',
  '/w95-icons/Letter.ico',
  '/w95-icons/Letters (3D).ico',
  '/w95-icons/Letters with phone.ico',
  '/w95-icons/Light beam.ico',
  '/w95-icons/Light pin sheet.ico',
  '/w95-icons/Link on Document with Earth.ico',
  '/w95-icons/Link on Fonts folder.ico',
  '/w95-icons/Link on Printers folder .ico',
  '/w95-icons/Link to MSN.ico',
  '/w95-icons/Link to.ico',
  '/w95-icons/List.ico',
  '/w95-icons/Lock and 2 keys.ico',
  '/w95-icons/Locked.ico',
  '/w95-icons/Logo.ico',
  '/w95-icons/MCI with phone.ico',
  '/w95-icons/MIDI keyboard & Computer.ico',
  '/w95-icons/MIDI keyboard (connected).ico',
  '/w95-icons/MIDI keyboard.ico',
  '/w95-icons/MS-DOS logo.ico',
  '/w95-icons/MSN.ico',
  '/w95-icons/MYICON.ico',
  '/w95-icons/Mail Search on Earth.ico',
  '/w95-icons/Mail catalog.ico',
  '/w95-icons/Mail text.ico',
  '/w95-icons/Mail with Credit Card.ico',
  '/w95-icons/Mail wizard deny.ico',
  '/w95-icons/Mail wizard.ico',
  '/w95-icons/Mail.ico',
  '/w95-icons/Mailbox with phone.ico',
  '/w95-icons/Mailbox.ico',
  '/w95-icons/Map-Network-Drive.png',
  '/w95-icons/Marking forms.ico',
  '/w95-icons/MasterCard.ico',
  '/w95-icons/Maximize.png',
  '/w95-icons/Microphone & Cassette.ico',
  '/w95-icons/Microphone.ico',
  '/w95-icons/Microsoft ERU.ico',
  '/w95-icons/Microsoft with Ball.ico',
  '/w95-icons/Minimize.png',
  '/w95-icons/Mouse LMB.ico',
  '/w95-icons/Mouse.ico',
  '/w95-icons/Move document with phone (green).ico',
  '/w95-icons/Move document with phone (pink).ico',
  '/w95-icons/Move document.ico',
  '/w95-icons/Move sheet.ico',
  '/w95-icons/Movie Frame (3-2-1).ico',
  '/w95-icons/Movie frame (cubes).ico',
  '/w95-icons/Movie frame (in hands).ico',
  '/w95-icons/Movie sheet.ico',
  '/w95-icons/Movie.ico',
  '/w95-icons/Moving letters.ico',
  '/w95-icons/Multimedia Drive.ico',
  '/w95-icons/Music Disc 2.ico',
  '/w95-icons/Music Disc.ico',
  '/w95-icons/Music sheet (black).ico',
  '/w95-icons/Music sheet (purple).ico',
  '/w95-icons/Mute volume.ico',
  '/w95-icons/My Computer.ico',
  '/w95-icons/Mystify.ico',
  '/w95-icons/Net cable.ico',
  '/w95-icons/Network Drive Error.ico',
  '/w95-icons/Network Drive.ico',
  '/w95-icons/Network Neighborhood (16x16px & 32x32px).ico',
  '/w95-icons/Network Neighborhood (48x48px).ico',
  '/w95-icons/New Folder 2.ico',
  '/w95-icons/New folder.ico',
  '/w95-icons/New letter.ico',
  '/w95-icons/News on Network Drive.ico',
  '/w95-icons/Newspaper (white 3D with letter).ico',
  '/w95-icons/Newspaper (white 3D).ico',
  '/w95-icons/Newspaper (yellow 3D).ico',
  '/w95-icons/Newspaper (yellow).ico',
  '/w95-icons/Newspaper with phone.ico',
  '/w95-icons/Night on computer.ico',
  '/w95-icons/Notepad document config.ico',
  '/w95-icons/Notepad document.ico',
  '/w95-icons/Notepad sheets.ico',
  '/w95-icons/Notepad writing.ico',
  '/w95-icons/Notepad.ico',
  '/w95-icons/Notepads.ico',
  '/w95-icons/Office progam.ico',
  '/w95-icons/Opened Folder.ico',
  '/w95-icons/Orb with phone.ico',
  '/w95-icons/Other abstract.ico',
  '/w95-icons/PHONE.ico',
  '/w95-icons/PRO_ORB.ico',
  '/w95-icons/Paint.ico',
  '/w95-icons/Paintbrish.ico',
  '/w95-icons/Painting.ico',
  '/w95-icons/Paper (check mark).ico',
  '/w95-icons/Paper (cross).ico',
  '/w95-icons/Paperclip.ico',
  '/w95-icons/Paste.png',
  '/w95-icons/People.ico',
  '/w95-icons/Petri Dish with phone.ico',
  '/w95-icons/Phone (2 of 5 diodes on).ico',
  '/w95-icons/Phone (all diodes off).ico',
  '/w95-icons/Phone (gray) dialing 2.ico',
  '/w95-icons/Phone (gray) dialing.ico',
  '/w95-icons/Phone (gray).ico',
  '/w95-icons/Phone dialing.ico',
  '/w95-icons/Phone input.ico',
  '/w95-icons/Pin program in Start Menu.ico',
  '/w95-icons/Pin sheet.ico',
  '/w95-icons/Pinned notes.ico',
  '/w95-icons/Pinned note.ico',
  '/w95-icons/Plug.ico',
  '/w95-icons/Plush bear.ico',
  '/w95-icons/Point on sheet.ico',
  '/w95-icons/Printer & Computer 2.ico',
  '/w95-icons/Printer & Computer.ico',
  '/w95-icons/Printer 2.ico',
  '/w95-icons/Printer 3.ico',
  '/w95-icons/Printer Input.ico',
  '/w95-icons/Printer Network.ico',
  '/w95-icons/Printer board in.ico',
  '/w95-icons/Printer board out.ico',
  '/w95-icons/Printer calendar.ico',
  '/w95-icons/Printer control list.ico',
  '/w95-icons/Printer help.ico',
  '/w95-icons/Printer monitor.ico',
  '/w95-icons/Printer rainbow.ico',
  '/w95-icons/Printer.ico',
  '/w95-icons/Printers folder.ico',
  '/w95-icons/Program list.ico',
  '/w95-icons/Program manager.ico',
  '/w95-icons/Program wait 2.ico',
  '/w95-icons/Program wait.ico',
  '/w95-icons/Program wizard.ico',
  '/w95-icons/Program.ico',
  '/w95-icons/Programs 2.ico',
  '/w95-icons/Programs.ico',
  '/w95-icons/Projector (gray) sheet.ico',
  '/w95-icons/Projector (green) sheet.ico',
  '/w95-icons/Projector (light-blue) sheet.ico',
  '/w95-icons/Projector (pink) sheet.ico',
  '/w95-icons/Projector 2.ico',
  '/w95-icons/Projector sheets.ico',
  '/w95-icons/Projector.ico',
  '/w95-icons/Properties.png',
  '/w95-icons/Pult.ico',
  '/w95-icons/Question.ico',
  '/w95-icons/Read.ico',
  '/w95-icons/Recycle Bin with document.ico',
  '/w95-icons/Recycle Bin with folder and document.ico',
  '/w95-icons/Recycle Bin with folder.ico',
  '/w95-icons/Recycle Bin with paper.ico',
  '/w95-icons/Recycle Bin with torned document and program.ico',
  '/w95-icons/Recycle Bin with torned documents.ico',
  '/w95-icons/Red Abstract.ico',
  '/w95-icons/Red phone and small Yellow phone.ico',
  '/w95-icons/Regedit file.ico',
  '/w95-icons/Regedit swap.ico',
  '/w95-icons/Regedit value (bin).ico',
  '/w95-icons/Regedit value (hex).ico',
  '/w95-icons/Regedit.ico',
  '/w95-icons/Remove Folder.ico',
  '/w95-icons/Remove fax.ico',
  '/w95-icons/Rename Folder.ico',
  '/w95-icons/Resize sheet (H).ico',
  '/w95-icons/Resize sheet (V).ico',
  '/w95-icons/Roadsign.ico',
  '/w95-icons/Safe.ico',
  '/w95-icons/Save Printer File.ico',
  '/w95-icons/Science with phone.ico',
  '/w95-icons/Scrap.ico',
  '/w95-icons/Screensaver.ico',
  '/w95-icons/Search folder.ico',
  '/w95-icons/Search for Printer 2.ico',
  '/w95-icons/Search for Printer.ico',
  '/w95-icons/Search in Regedit.ico',
  '/w95-icons/Search in sheet (pink).ico',
  '/w95-icons/Search letter.ico',
  '/w95-icons/Search letters.ico',
  '/w95-icons/Search on Disc.ico',
  '/w95-icons/Search on Earth.ico',
  '/w95-icons/Search on computer 2.ico',
  '/w95-icons/Search on computer.ico',
  '/w95-icons/Settings.ico',
  '/w95-icons/Shared.ico',
  '/w95-icons/Sheet print format (double H).ico',
  '/w95-icons/Sheet print format (double V).ico',
  '/w95-icons/Sheet print format (long H).ico',
  '/w95-icons/Sheet print format (long V).ico',
  '/w95-icons/Sheet print format (short H).ico',
  '/w95-icons/Sheet print format (short V).ico',
  '/w95-icons/Sheet with cubes 2 (locked).ico',
  '/w95-icons/Sheet with cubes 2.ico',
  '/w95-icons/Sheet with cubes.ico',
  '/w95-icons/Sheet with home.ico',
  '/w95-icons/Sheet with painting.ico',
  '/w95-icons/Sheets & Documents.ico',
  '/w95-icons/Sheets conflict 2.ico',
  '/w95-icons/Shortcut (big).ico',
  '/w95-icons/Shortcut on blue.ico',
  '/w95-icons/Shortcut.ico',
  '/w95-icons/SiS.ico',
  '/w95-icons/Sign Printer.ico',
  '/w95-icons/Sign white letter.ico',
  '/w95-icons/Smiley face.ico',
  '/w95-icons/Sound computer.ico',
  '/w95-icons/Sound program.ico',
  '/w95-icons/Star stamp.ico',
  '/w95-icons/Star.ico',
  '/w95-icons/Starfield.ico',
  '/w95-icons/Stopwatch.ico',
  '/w95-icons/Stuff.ico',
  '/w95-icons/Sync Earth Fail.ico',
  '/w95-icons/Sync Earth.ico',
  '/w95-icons/System to folder.ico',
  '/w95-icons/TWUNK.ico',
  '/w95-icons/Tablet Write.ico',
  '/w95-icons/Task Manager.ico',
  '/w95-icons/Text field sheet 2.ico',
  '/w95-icons/Text field sheet 3.ico',
  '/w95-icons/Text field sheet.ico',
  '/w95-icons/Text in letter.ico',
  '/w95-icons/Text sheet (H).ico',
  '/w95-icons/Text sheet (V).ico',
  '/w95-icons/Text stamp.ico',
  '/w95-icons/Text to letter.ico',
  '/w95-icons/Tip of the Day.ico',
  '/w95-icons/Tree.ico',
  '/w95-icons/TrueType font (blue).ico',
  '/w95-icons/TrueType font (green).ico',
  '/w95-icons/TrueType font (logo).ico',
  '/w95-icons/Turn Off Computer (display only).ico',
  '/w95-icons/Turn Off Computer (full).ico',
  '/w95-icons/UX Earth.ico',
  '/w95-icons/Umbrella with phone.ico',
  '/w95-icons/Uninstall Recycle Bin.ico',
  '/w95-icons/Unlock printer.ico',
  '/w95-icons/User documents.ico',
  '/w95-icons/User program notififcation.ico',
  '/w95-icons/User program.ico',
  '/w95-icons/User with computer.ico',
  '/w95-icons/User.ico',
  '/w95-icons/Users with cursor.ico',
  '/w95-icons/VBS program.ico',
  '/w95-icons/VBS programs 2.ico',
  '/w95-icons/VBS programs.ico',
  '/w95-icons/Visa.ico',
  '/w95-icons/Volume (green) sheet.ico',
  '/w95-icons/Volume (light-blue) sheet.ico',
  '/w95-icons/Volume (pink) sheet.ico',
  '/w95-icons/Volume (yellow) sheet.ico',
  '/w95-icons/Volume Controls 2.ico',
  '/w95-icons/Volume Controls.ico',
  '/w95-icons/Volume Dialog.ico',
  '/w95-icons/Volume Disc.ico',
  '/w95-icons/Volume Speaker.ico',
  '/w95-icons/Volume Up.ico',
  '/w95-icons/Volume Wave (gray).ico',
  '/w95-icons/Volume Wave.ico',
  '/w95-icons/Volume sheets.ico',
  '/w95-icons/Volume.ico',
  '/w95-icons/WANG catalog.ico',
  '/w95-icons/WANG device.ico',
  '/w95-icons/Warning.ico',
  '/w95-icons/Web-Document.ico',
  '/w95-icons/Web-document 2.ico',
  '/w95-icons/Web-document move.ico',
  '/w95-icons/Web-document program.ico',
  '/w95-icons/Web-documents folder 2.ico',
  '/w95-icons/Web-documents folder.ico',
  '/w95-icons/Web-documents.ico',
  '/w95-icons/Welcome program.ico',
  '/w95-icons/White letter (opened with text).ico',
  '/w95-icons/White letter (opened).ico',
  '/w95-icons/White letter.ico',
  '/w95-icons/Windiws logo (with text) 2.ico',
  '/w95-icons/Windows 95 logo.ico',
  '/w95-icons/Windows Disc.ico',
  '/w95-icons/Windows Key (32x32).ico',
  '/w95-icons/Windows Key (48x48).ico',
  '/w95-icons/Windows document.ico',
  '/w95-icons/Windows logo (with text).ico',
  '/w95-icons/Windows logo (without text).ico',
  '/w95-icons/WordPad document.ico',
  '/w95-icons/WordPad sheet.ico',
  '/w95-icons/WordPad.ico',
  '/w95-icons/Write program.ico',
  '/w95-icons/Writing forms with Fax.ico',
  '/w95-icons/Writing on list with figures.ico',
  '/w95-icons/Writing on sheet.ico',
  '/w95-icons/Writing sheet.ico',
  '/w95-icons/w!.ico',
]

const getRandomFileIcon = () =>
  fileIcons[Math.floor(Math.random() * fileIcons.length)]

type Props = {}

export const FileIcon: React.FC<Props> = ({}) => {
  const iconSrc = getRandomFileIcon()
  return (
    <img
      src={iconSrc}
      data-img={iconSrc}
      alt=""
      width={25}
      height={25}
      className="m-auto"
    />
  )
}
